development:
  adapter: postgresql
  encoding: unicode
  database: mrdeolho_development
  pool: 5
  username: runeroniek 
  #password:
  host: localhost

test:
  adapter: postgresql
  encoding: unicode
  database: mrdeolho_test
  pool: 5
  username: runeroniek 
  #password:
  min_messages: WARNING
  host: localhost

